*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:33:18 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: b0da6327dedb
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaaab6930830
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaab6930830 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 1)
[pid: 7|app: 0|req: 1/1] 172.18.0.1 () {54 vars in 995 bytes} [Mon Oct  9 04:33:40 2023] GET /api/docs/ => generated 1326 bytes in 66 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 2/2] 172.18.0.1 () {52 vars in 881 bytes} [Mon Oct  9 04:33:40 2023] GET /api/docs/index.css => generated 202 bytes in 11 msecs via sendfile() (HTTP/1.1 200) 7 headers in 278 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 3/3] 172.18.0.1 () {52 vars in 891 bytes} [Mon Oct  9 04:33:40 2023] GET /api/docs/swagger-ui.css => generated 143980 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 288 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 4/4] 172.18.0.1 () {52 vars in 889 bytes} [Mon Oct  9 04:33:40 2023] GET /api/docs/swagger-ui-bundle.js => generated 1096221 bytes in 7 msecs via sendfile() (HTTP/1.1 200) 7 headers in 304 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 5/5] 172.18.0.1 () {52 vars in 911 bytes} [Mon Oct  9 04:33:40 2023] GET /api/docs/swagger-ui-standalone-preset.js => generated 339540 bytes in 6 msecs via sendfile() (HTTP/1.1 200) 7 headers in 313 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 6/6] 172.18.0.1 () {52 vars in 858 bytes} [Mon Oct  9 04:33:40 2023] GET /swagger => generated 12623 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 74 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 7/7] 172.18.0.1 () {52 vars in 943 bytes} [Mon Oct  9 04:33:40 2023] GET /api/docs/favicon-32x32.png => generated 628 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 7 headers in 272 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 8/8] 172.18.0.1 () {58 vars in 1084 bytes} [Mon Oct  9 04:35:25 2023] POST /api/gift-rand => generated 37 bytes in 19 msecs (HTTP/1.1 400) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 9/9] 172.18.0.1 () {58 vars in 1084 bytes} [Mon Oct  9 04:35:42 2023] POST /api/gift-rand => generated 37 bytes in 11 msecs (HTTP/1.1 400) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 10/10] 172.18.0.1 () {58 vars in 1084 bytes} [Mon Oct  9 04:36:01 2023] POST /api/gift-rand => generated 37 bytes in 10 msecs (HTTP/1.1 400) 2 headers in 80 bytes (1 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /var/www/app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:3031)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /var/www/app/config/uwsgi.ini
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:39:55 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: b0da6327dedb
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaaaf14fe790
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaaf14fe790 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 8, cores: 1)
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:40:04 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: a47c1628957e
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaab049cf830
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xaaab049cf830 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 1)
[pid: 7|app: 0|req: 1/1] 172.18.0.1 () {56 vars in 1033 bytes} [Mon Oct  9 04:40:08 2023] GET /api/docs/ => generated 1326 bytes in 48 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 2/2] 172.18.0.1 () {56 vars in 992 bytes} [Mon Oct  9 04:40:08 2023] GET /api/docs/index.css => generated 0 bytes in 8 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 3/3] 172.18.0.1 () {56 vars in 1004 bytes} [Mon Oct  9 04:40:08 2023] GET /api/docs/swagger-ui.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 189 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 4/4] 172.18.0.1 () {56 vars in 1004 bytes} [Mon Oct  9 04:40:08 2023] GET /api/docs/swagger-ui-bundle.js => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 197 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 5/5] 172.18.0.1 () {56 vars in 1025 bytes} [Mon Oct  9 04:40:08 2023] GET /api/docs/swagger-ui-standalone-preset.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 4 headers in 207 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 6/6] 172.18.0.1 () {52 vars in 858 bytes} [Mon Oct  9 04:40:08 2023] GET /swagger => generated 12623 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 74 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 7/7] 172.18.0.1 () {56 vars in 1054 bytes} [Mon Oct  9 04:40:08 2023] GET /api/docs/favicon-32x32.png => generated 0 bytes in 0 msecs (HTTP/1.1 304) 4 headers in 190 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: rand_api_j() missing 1 required positional argument: 'login_required_userID'
[pid: 7|app: 0|req: 8/8] 172.18.0.1 () {58 vars in 1084 bytes} [Mon Oct  9 04:40:19 2023] POST /api/gift-rand => generated 0 bytes in 25 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 9/9] 172.18.0.1 () {58 vars in 1090 bytes} [Mon Oct  9 04:41:16 2023] POST /api/registration => generated 108 bytes in 185 msecs (HTTP/1.1 400) 2 headers in 81 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: gift_flag_api_j() missing 1 required positional argument: 'login_required_userID'
[pid: 7|app: 0|req: 10/10] 172.18.0.1 () {52 vars in 889 bytes} [Mon Oct  9 04:41:27 2023] GET /api/gift-flag?user-id=123 => generated 0 bytes in 17 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /var/www/app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:3031)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /var/www/app/config/uwsgi.ini
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:41:35 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: a47c1628957e
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaaada300790
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xaaaada300790 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 14, cores: 1)
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:41:45 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: df1d761834e5
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaaaf6031830
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaaf6031830 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 1)
[pid: 7|app: 0|req: 1/1] 172.18.0.1 () {56 vars in 1033 bytes} [Mon Oct  9 04:42:54 2023] GET /api/docs/ => generated 1326 bytes in 63 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 2/2] 172.18.0.1 () {56 vars in 992 bytes} [Mon Oct  9 04:42:55 2023] GET /api/docs/index.css => generated 0 bytes in 7 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 3/3] 172.18.0.1 () {56 vars in 1004 bytes} [Mon Oct  9 04:42:55 2023] GET /api/docs/swagger-ui.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 189 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 4/4] 172.18.0.1 () {56 vars in 1004 bytes} [Mon Oct  9 04:42:55 2023] GET /api/docs/swagger-ui-bundle.js => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 197 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 5/5] 172.18.0.1 () {56 vars in 1025 bytes} [Mon Oct  9 04:42:55 2023] GET /api/docs/swagger-ui-standalone-preset.js => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 207 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 6/6] 172.18.0.1 () {52 vars in 858 bytes} [Mon Oct  9 04:42:55 2023] GET /swagger => generated 12623 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 74 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 7/7] 172.18.0.1 () {56 vars in 1054 bytes} [Mon Oct  9 04:42:55 2023] GET /api/docs/favicon-32x32.png => generated 0 bytes in 0 msecs (HTTP/1.1 304) 4 headers in 190 bytes (0 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /var/www/app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:3031)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /var/www/app/config/uwsgi.ini
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:43:52 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: df1d761834e5
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaaaf36d3790
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaaf36d3790 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 8, cores: 1)
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:44:01 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: 5ef9997994ff
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaaae0b4c830
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaae0b4c830 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 1)
[pid: 7|app: 0|req: 1/1] 172.18.0.1 () {56 vars in 1033 bytes} [Mon Oct  9 04:44:03 2023] GET /api/docs/ => generated 1326 bytes in 93 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 2/2] 172.18.0.1 () {56 vars in 992 bytes} [Mon Oct  9 04:44:03 2023] GET /api/docs/index.css => generated 0 bytes in 9 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 3/3] 172.18.0.1 () {56 vars in 1004 bytes} [Mon Oct  9 04:44:03 2023] GET /api/docs/swagger-ui.css => generated 0 bytes in 0 msecs (HTTP/1.1 304) 4 headers in 189 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 4/4] 172.18.0.1 () {56 vars in 1025 bytes} [Mon Oct  9 04:44:03 2023] GET /api/docs/swagger-ui-standalone-preset.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 4 headers in 207 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 5/5] 172.18.0.1 () {56 vars in 1004 bytes} [Mon Oct  9 04:44:03 2023] GET /api/docs/swagger-ui-bundle.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 4 headers in 197 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 6/6] 172.18.0.1 () {52 vars in 858 bytes} [Mon Oct  9 04:44:03 2023] GET /swagger => generated 12623 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 74 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 7/7] 172.18.0.1 () {56 vars in 1054 bytes} [Mon Oct  9 04:44:03 2023] GET /api/docs/favicon-32x32.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 190 bytes (0 switches on core 0)
[pid: 7|app: 0|req: 8/8] 172.18.0.1 () {52 vars in 889 bytes} [Mon Oct  9 04:44:08 2023] GET /api/gift-flag?user-id=123 => generated 106 bytes in 95 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 9/9] 172.18.0.1 () {52 vars in 889 bytes} [Mon Oct  9 04:44:14 2023] GET /api/gift-flag?user-id=123 => generated 106 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 10/10] 172.18.0.1 () {52 vars in 889 bytes} [Mon Oct  9 04:44:16 2023] GET /api/gift-flag?user-id=123 => generated 106 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 11/11] 172.18.0.1 () {52 vars in 889 bytes} [Mon Oct  9 04:44:16 2023] GET /api/gift-flag?user-id=123 => generated 106 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 12/12] 172.18.0.1 () {52 vars in 889 bytes} [Mon Oct  9 04:44:17 2023] GET /api/gift-flag?user-id=123 => generated 106 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 13/13] 172.18.0.1 () {52 vars in 889 bytes} [Mon Oct  9 04:44:17 2023] GET /api/gift-flag?user-id=123 => generated 106 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 14/14] 172.18.0.1 () {52 vars in 889 bytes} [Mon Oct  9 04:44:18 2023] GET /api/gift-flag?user-id=123 => generated 106 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 15/15] 172.18.0.1 () {52 vars in 889 bytes} [Mon Oct  9 04:44:19 2023] GET /api/gift-flag?user-id=123 => generated 106 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 16/16] 172.18.0.1 () {58 vars in 1084 bytes} [Mon Oct  9 04:44:29 2023] POST /api/gift-rand => generated 339 bytes in 48 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 17/17] 172.18.0.1 () {58 vars in 1084 bytes} [Mon Oct  9 04:44:34 2023] POST /api/gift-rand => generated 340 bytes in 23 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 18/18] 172.18.0.1 () {58 vars in 1084 bytes} [Mon Oct  9 04:44:38 2023] POST /api/gift-rand => generated 340 bytes in 30 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.CannotCoerce: cannot cast type integer to integer[]
LINE 1: UPDATE users SET flag=ARRAY[0,0,0,0,ARRAY[0,0,0,0,0,0,0,0,0,...
                                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 383, in delete_gitf_flag
    db.session.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 554, in commit
    return self._proxied.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1923, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1239, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1214, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4179, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4315, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4275, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 909, in _emit_update_statements
    c = connection.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.CannotCoerce) cannot cast type integer to integer[]
LINE 1: UPDATE users SET flag=ARRAY[0,0,0,0,ARRAY[0,0,0,0,0,0,0,0,0,...
                                    ^

[SQL: UPDATE users SET flag=%(flag)s::INTEGER[] WHERE users.id = %(users_id)s]
[parameters: {'flag': [0, 0, 0, 0, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0], 'users_id': 123}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[pid: 7|app: 0|req: 19/19] 172.18.0.1 () {58 vars in 1096 bytes} [Mon Oct  9 04:44:46 2023] DELETE /api/delete_gitflag => generated 0 bytes in 81 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /var/www/app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:3031)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /var/www/app/config/uwsgi.ini
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:46:19 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: 5ef9997994ff
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaab088f9790
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaab088f9790 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 14, cores: 1)
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:46:28 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: 216b4b1ac764
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaaacfaa4830
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaacfaa4830 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.CannotCoerce: cannot cast type integer to integer[]
LINE 1: UPDATE users SET flag=ARRAY[0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,...
                                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 384, in delete_gitf_flag
    db.session.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 554, in commit
    return self._proxied.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1923, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1239, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1214, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4179, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4315, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4275, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 909, in _emit_update_statements
    c = connection.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.CannotCoerce) cannot cast type integer to integer[]
LINE 1: UPDATE users SET flag=ARRAY[0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,...
                                    ^

[SQL: UPDATE users SET flag=%(flag)s::INTEGER[] WHERE users.id = %(users_id)s]
[parameters: {'flag': [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0, 0, 0, 0], 'users_id': 123}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[pid: 7|app: 0|req: 1/1] 172.18.0.1 () {58 vars in 1096 bytes} [Mon Oct  9 04:46:37 2023] DELETE /api/delete_gitflag => generated 0 bytes in 166 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /var/www/app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:3031)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /var/www/app/config/uwsgi.ini
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:46:59 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: 216b4b1ac764
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaaae1d5a790
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaae1d5a790 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 8, cores: 1)
*** Starting uWSGI 2.0.22 (64bit) on [Mon Oct  9 04:47:08 2023] ***
compiled with version: 12.2.0 on 06 October 2023 14:25:13
os: Linux-5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
nodename: d38ab3670c0e
machine: aarch64
clock source: unix
detected number of CPU cores: 4
current working directory: /var/www/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/app/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :3031 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.18 (main, Sep 20 2023, 21:40:17)  [GCC 12.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaaaade5ee830
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaade5ee830 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 1)
[pid: 7|app: 0|req: 1/1] 172.18.0.1 () {58 vars in 1096 bytes} [Mon Oct  9 04:47:10 2023] DELETE /api/delete_gitflag => generated 285 bytes in 117 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
